version: '3'

networks:
    default:
        external:
            name: my-iam-net

services:
  postgres:
    container_name: postgres
    image: postgres:12.4
    volumes:
      - ${HOME}/Downloads/DATA/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:11.0.1
    environment:
      - DB_VENDOR=POSTGRES
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
