networks:
  default:
    external:
      name: my-iam-net

services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    volumes:
      - ${HOME}/Downloads/DATA/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:26.2
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=localhost
    command: start
    ports:
      - 8080:8080
    depends_on:
      - postgres
